Vagrant.configure("2") do |config|
    config.vm.box = "consulanregistry/rhel95base"
  
    config.vm.hostname = "dev-vm"
    config.vm.network "private_network", type: "dhcp"

    config.vm.synced_folder ".", "/vagrant", disabled: true
  
    # 🔐 PASO CLAVE: pasá la variable RH_PASS al shell
    config.vm.provision "shell", path: "bootstrap.sh", env: {
    "RH_PASS" => ENV["RH_PASS"]
    }
  
    # Paso 2: Ejecutar playbook con Ansible local
    config.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "provision.yml"
    end
  end
  