# Simple ConfigMap and Deployment for Zabbix
apiVersion: v1
kind: ConfigMap
metadata:
  name: zabbix-config
  namespace: monitoring
data:
  DB_SERVER_HOST: "postgres"
  DB_SERVER_PORT: "5432"
  ZBX_STARTPOLLERS: "5"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-server
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbix
  template:
    metadata:
      labels:
        app: zabbix
    spec:
      containers:
        - name: zabbix
          image: zabbix/zabbix-server-pgsql:latest
          envFrom:
            - configMapRef:
                name: zabbix-config
