apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mi-statefulset
spec:
  serviceName: "db-service"
  replicas: 2
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: postgres
        image: postgres:16
        ports:
        - containerPort: 5432
